import { Injectable } from '@angular/core';
import { Job } from './job.model';

@Injectable({
  providedIn: 'root'
})
export class JobService {

  private jobs: Job[] = [
    {
      id: 1,
      title: 'Développeur Full-Stack',
      description: 'Développement d’applications web en Angular et Spring Boot.',
      company: 'TechAfrik',
      location: 'Douala, Cameroun',
      salary: '500 000 FCFA/mois',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-01',
    },
    {
      id: 2,
      title: 'Chargé de Communication',
      description: 'Mise en place de campagnes digitales.',
      company: 'MediaVision',
      location: 'Dakar, Sénégal',
      salary: '350 000 FCFA/mois',
      jobtyp: ['CDD'],
      Arbeitszeit: ['Temps partiel'],
      veroeffentlicht: '2025-05-04',
    },
    {
      id: 3,
      title: 'Responsable RH',
      description: 'Gestion des recrutements et formations internes.',
      company: 'Orange Bénin',
      location: 'Cotonou, Bénin',
      salary: '600 000 FCFA/mois',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-06',
    },
    {
      id: 4,
      title: 'Comptable Senior',
      description: 'Tenue de la comptabilité générale et analytique.',
      company: 'AfricAudit',
      location: 'Ouagadougou, Burkina Faso',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-08',
    },
    {
      id: 5,
      title: 'Data Analyst',
      description: 'Analyse de données financières et commerciales.',
      company: 'InnovaData',
      location: 'Abidjan, Côte d’Ivoire',
      salary: '700 000 FCFA/mois',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-05',
    },
    {
      id: 6,
      title: 'Assistant Administratif',
      description: 'Gestion des dossiers, courriers et appels.',
      company: 'Cabinet KDS',
      location: 'Bamako, Mali',
      jobtyp: ['CDD'],
      Arbeitszeit: ['Temps partiel'],
      veroeffentlicht: '2025-05-03',
    },
    {
      id: 7,
      title: 'Technicien Réseau',
      description: 'Installation et maintenance des réseaux informatiques.',
      company: 'NetAfrique',
      location: 'Lomé, Togo',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-04-29',
    },
    {
      id: 8,
      title: 'Secrétaire bilingue',
      description: 'Accueil, gestion d’agenda et traduction FR/EN.',
      company: 'Global Services',
      location: 'Libreville, Gabon',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-07',
    },
    {
      id: 9,
      title: 'Agent commercial',
      description: 'Prospection et fidélisation clientèle.',
      company: 'CamerMarket',
      location: 'Yaoundé, Cameroun',
      salary: '300 000 FCFA + primes',
      jobtyp: ['Stage', 'CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-10',
    },
    {
      id: 10,
      title: 'Responsable logistique',
      description: 'Gestion des flux, stocks, transport.',
      company: 'Afrilog',
      location: 'Niamey, Niger',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-04-25',
    },
    {
      id: 11,
      title: 'UX/UI Designer',
      description: 'Création d’interfaces web ergonomiques.',
      company: 'DesignUp',
      location: 'Kigali, Rwanda',
      jobtyp: ['Freelance'],
      Arbeitszeit: ['Temps partiel'],
      veroeffentlicht: '2025-05-02',
    },
    {
      id: 12,
      title: 'Formateur bureautique',
      description: 'Formation en Word, Excel, PowerPoint.',
      company: 'SkillAfrique',
      location: 'Kinshasa, RDC',
      jobtyp: ['CDD'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-04-30',
    },
    {
      id: 13,
      title: 'Chauffeur livreur',
      description: 'Livraison de colis en moto ou véhicule.',
      company: 'Express Cargo',
      location: 'Nairobi, Kenya',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-06',
    },
    {
      id: 14,
      title: 'Community Manager',
      description: 'Animation de réseaux sociaux.',
      company: 'DigitAfrik',
      location: 'Accra, Ghana',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps partiel'],
      veroeffentlicht: '2025-05-04',
    },
    {
      id: 15,
      title: 'Ingénieur logiciel',
      description: 'Conception de logiciels métiers.',
      company: 'SmartDev',
      location: 'Tunis, Tunisie',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-01',
    },
    {
      id: 16,
      title: 'Chargé de clientèle',
      description: 'Support client et gestion des réclamations.',
      company: 'BankAfrica',
      location: 'N’Djamena, Tchad',
      jobtyp: ['CDD'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-03',
    },
    {
      id: 17,
      title: 'Agent de sécurité',
      description: 'Surveillance et contrôle des accès.',
      company: 'Sécuris',
      location: 'Conakry, Guinée',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-04-28',
    },
    {
      id: 18,
      title: 'Webmaster',
      description: 'Gestion technique d’un site vitrine.',
      company: 'WebMaster Africa',
      location: 'Antananarivo, Madagascar',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-05',
    },
    {
      id: 19,
      title: 'Responsable Qualité',
      description: 'Suivi et amélioration des procédures ISO.',
      company: 'QualiPlus',
      location: 'Alger, Algérie',
      jobtyp: ['CDI'],
      Arbeitszeit: ['Temps plein'],
      veroeffentlicht: '2025-05-02',
    },
    {
      id: 20,
      title: 'Graphiste',
      description: 'Création de visuels print et digitaux.',
      company: 'Studio Creativ',
      location: 'Maputo, Mozambique',
      jobtyp: ['Freelance'],
      Arbeitszeit: ['Temps partiel'],
      veroeffentlicht: '2025-05-08',
    }
  ];

  getJobs(): Job[] {
    return this.jobs;
  };

  getJobById(id: number): Job | undefined {
    return this.jobs.find(job => job.id === id);
  }
}
